apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: u2c0e6vh2-python 
  janus-idp.io/tekton: u2c0e6vh2-python
  backstage.io/kubernetes-id: u2c0e6vh2-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: u2c0e6vh2-python
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml